In [1]:
# Import the necessary libraries
import numpy as np
import pandas as pd
import sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import fetch_openml
from sklearn.utils import check_random_state
from sklearn.model_selection import train_test_split

# Importing the Data

The research question is can we use algorithms and compute to identify clothing items? Specifically, can we determine which algorithm and compute methodology provides us the most efficient approach for classifying simple fashion images?

In [2]:
# import the Fashion-Mnist Data fro Open ML
X, y = fetch_openml('Fashion-MNIST', version=1, return_X_y=True)

In [4]:
train_samples = 60000

In [5]:
# create the training and testing split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, train_size=train_samples, test_size=10000)

# Running Various Models on the Fashion-MNIST Data:

## Random Forest

In [6]:
# RANDOM FOREST (Code provided my Jon Fox)
from sklearn.ensemble import RandomForestClassifier 
forest = RandomForestClassifier(n_estimators = 500)
forest.fit(X_train, y_train)
print('Score: ', forest.score(X_test, y_test))
predictions = forest.predict(X_test)

Score:  0.8889


## K-Nearest Neighbors


In [7]:
# K-Nearest Neighbors (Code provided my Jon Fox)
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X, y)
neigh.score(X, y)


0.9205428571428571

## Bayes

In [8]:
# import packages from sklearn
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [9]:
# MODEL (Code provided my Jon Fox)

# Initialize our classifier
gnb = GaussianNB()

# Train our classifier
model = gnb.fit(X_train, y_train)

In [10]:
# MODEL

# Make predictions
preds = gnb.predict(X_test)
# print(preds)

In [12]:
# MODEL

# Evaluate accuracy
print(accuracy_score(y_test, preds))

0.6184


In [18]:
# INTERPRET

expected = y_test
predicted = preds
print(sklearn.metrics.confusion_matrix(expected, predicted))

[[618  35  31 187  75   0  14   0  29   0]
 [  2 926  11  47   3   0   6   0   0   0]
 [  1   6 323  75 536   0  24   0  15   0]
 [  8 254   7 710  26   0   3   0   2   0]
 [  1  28  44 150 717   0   5   0   8   0]
 [  0   1   1   1   0 253   3 696  14  49]
 [129  22 118 215 438   0  51   0  44   0]
 [  0   0   0   0   0   6   0 966   2  16]
 [  0   3  24 100 140   4  34   1 773   0]
 [  0   0   2   0   0  12   1 304   6 644]]
